[project]
name = "multiple-scraper"
version = "0.1.0"
description = "Scraper academic project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    'asyncpg',
    "beautifulsoup4",
    "pandas",
    "cloudscraper",
    "openpyxl>=3.1.5",
    "urllib3>=2.5.0",
    "rich>=14.1.0",
    "httpx[http2]>=0.28.1",
    "selectolax>=0.3.34",
    "setuptools>=80.9.0",
    "playwright>=1.55.0",
    "asyncio>=4.0.0",
    "python-dotenv>=1.2.1",
    "sqlalchemy[asyncio]>=2.0",
    "aiosqlite>=0.20.0",
    "python-telegram-bot[job-queue]>=21.0",
    "truststore>=0.9.1",
    "curl-cffi>=0.7.0",
]
